version: '3'

networks:
    mynet:
        external: true

services:
        prometheus:
                image: prom/prometheus
                volumes:
                        - /swarm/volumes/prometheus/:/etc/prometheus/
                        - prometheus_data:/prometheus
                command: ["-config.file=/etc/prometheus/prometheus.yml", "-storage.local.path=/prometheus", "-alertmanager.url=http://alertmanager:9093", "-storage.local.memory-chunks=100000"]
                        #- '-config.file=/etc/prometheus/prometheus.yml'
                        #- '-storage.local.path=/prometheus'
                        #- '-alertmanager.url=http://alertmanager:9093'
                        #- '-storage.local.memory-chunks=100000'
                ports:
                        - 9090:9090
                networks:
                        - mynet
                labels:
                        org.label-schema.group: "monitoring"
                deploy:
                        placement:
                                constraints: [node.hostname == swarm-monitor.local]

        alertmanager:
                image: prom/alertmanager
                volumes:
                        - /swarm/volumes/alertmanager/:/etc/alertmanager/
                command: ["-config.file=/etc/alertmanager/config.yml", "-storage.path=/alertmanager"]
                        #- '-config.file=/etc/alertmanager/config.yml'
                        #- '-storage.path=/alertmanager'
                ports:
                        - 9093:9093
                networks:
                        - mynet
                labels:
                        org.label-schema.group: "monitoring"
                deploy:
                        placement:
                                constraints: [node.hostname == swarm-monitor.local]

        nodeexporter:
                image: prom/node-exporter
                restart: unless-stopped
                ports:
                        - 9100
                networks:
                        - mynet
                labels:
                        org.label-schema.group: "monitoring"
                deploy:
                        placement:
                                constraints: [node.hostname == swarm-monitor.local]

        cadvisor:
                image: google/cadvisor:v0.24.1
                volumes:
                        - /:/rootfs:ro
                        - /var/run:/var/run:rw
                        - /sys:/sys:ro
                        - /var/lib/docker/:/var/lib/docker:ro
                ports:
                        - 8080
                networks:
                        - mynet
                labels:
                        org.label-schema.group: "monitoring"
                deploy:
                        placement:
                                constraints: [node.hostname == swarm-monitor.local]

        grafana:
                image: grafana/grafana
                volumes:
                        - grafana_data:/var/lib/grafana
                env_file:
                        - user.config
                ports:
                        - 3000:3000
                networks:
                        - mynet
                labels:
                        org.label-schema.group: "monitoring"
                deploy:
                        placement:
                                constraints: [node.hostname == swarm-monitor.local]

#networks:
#        mynet:
volumes:
        grafana_data:
        prometheus_data:
