version: '2'
services:
        prometheus:
                image: prom/prometheus
                restart: always
                network_mode: "host"
                volumes:
                        - /data/prometheus/:/etc/prometheus/
                        - /data/prometheus_data:/prometheus
                command: ["-config.file=/etc/prometheus/prometheus.yml", "-storage.local.path=/prometheus"]
                ports:
                        - 9090:9090
